### ISSUE TITLE
"xdelta3: source file too short: XD3_INVALID_INPUT"

### ISSUE THREAD

**Issue by SomaBenjamin** [berthrage/Devil-May-Cry-3-Crimson#119]
I'm getting this when trying to install the mod:
Applying xdelta3 patch to dmc3.exe...
xdelta3: source file too short: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
Failed to patch dmc3.exe!
This is a fresh install of DMC HD Collection, so I have no idea why this is happening.

![Image](https://github.com/user-attachments/assets/d52a3924-f7d3-4894-a158-db9bb6a6562b)

**Comment by ProjectXsent** [comment]
Did you run apply_batch.bat as Admin?

**Comment by SomaBenjamin** [comment]
> I got this error, i found it require live version *.exe from Steam, i did backup *.exe last time downgrade for DDMK.

But I just installed this, it's the latest version of HD Collection.

> Did you run apply_batch.bat as Admin?

![Image](https://github.com/user-attachments/assets/0c8fa952-890a-4220-b417-aa25c9a57e29)
This is what happens instead.

**Comment by ProjectXsent** [comment]
> ![Image](https://github.com/user-attachments/assets/0c8fa952-890a-4220-b417-aa25c9a57e29) This is what happens instead.

The xdelta exe went missing.

**Comment by MlKaya** [comment]
same thing happened with me, can't figure it out:(

**Comment by MlKaya** [comment]
![Image](https://github.com/user-attachments/assets/9e7bff6d-afa5-4e37-9e55-8e95637c4f5d)

**Comment by MlKaya** [comment]
xdelta3-3.0.11-x86_64.exe is on the directory but I get this error

**Comment by SomaBenjamin** [comment]
> > ![Image](https://github.com/user-attachments/assets/0c8fa952-890a-4220-b417-aa25c9a57e29) This is what happens instead.
> 
> The xdelta exe went missing.
It's not, it still gets found when I use it without admin permission.

**Comment by dssworkshop** [comment]
> > I got this error, i found it require live version *.exe from Steam, i did backup *.exe last time downgrade for DDMK.
> 
> But I just installed this, it's the latest version of HD Collection.
> 
> > Did you run apply_batch.bat as Admin?
> 
> ![Image](https://github.com/user-attachments/assets/0c8fa952-890a-4220-b417-aa25c9a57e29) This is what happens instead.



apply_patch.bat will remove dmc3.exe and dmcLauncher.exe after error, make sure bakcup before modding.

did you run the game before modding it?

**Comment by MlKaya** [comment]
does running the game once without mods is required?

**Comment by ProjectXsent** [comment]
I skipped the first apply_patch procedure because I already got the downgraded exes from [here](https://github.com/serpentiem/ddmk/issues/348#issuecomment-2832584543) and I only extracted the Crimson and data folder, Crimson.dll, dinput8.dll, libmpg123-0.dll and the 2 SDL2 dll files. I also ran the apply_patch inside the data folder then the game ran fine with the mod on my end.

**Comment by MlKaya** [comment]
THAT DID IT, THANK YOU SO MUCH MAN

**Comment by Delta21X** [comment]
> I skipped the first apply_patch procedure because I already got the downgraded exes from [here](https://github.com/serpentiem/ddmk/issues/348#issuecomment-2832584543) and I only extracted the Crimson and data folder, Crimson.dll, dinput8.dll, libmpg123-0.dll and the 2 SDL2 dll files. I also ran the apply_patch inside the data folder then the game ran fine with the mod on my end.

this didn't work for me, which downgraded files did you install? or maybe there's something else wrong with mine, but it was a fresh install, then i did your steps and it still didn't work, my game crashes seconds after dmc3 opens. i see the little menu showing the mod installed and the loading screen behind it before my game closes

**Comment by ProjectXsent** [comment]
> this didn't work for me, which downgraded files did you install? or maybe there's something else wrong with mine, but it was a fresh install, then i did your steps and it still didn't work, my game crashes seconds after dmc3 opens. i see the little menu showing the mod installed and the loading screen behind it before my game closes

I used both zips and both worked. Have you installed the DirectX End User Runtime and Visual C++ Redistributable All in One?

I also made sure to remove all traces of mods from DDMK.

**Comment by ProjectXsent** [comment]
> 
> yes, i installed them and restarted my computer earlier

Since the game's a fresh install, can you try verifying the game files then re-install the mod?

**Comment by Delta21X** [comment]
> > yes, i installed them and restarted my computer earlier
> 
> Since the game's a fresh install, can you try verifying the game files then re-install the mod?

i've tried this multiple times, but i can try once more

**Comment by Delta21X** [comment]
> > > yes, i installed them and restarted my computer earlier
> > 
> > 
> > Since the game's a fresh install, can you try verifying the game files then re-install the mod?
> 
> i've tried this multiple times, but i can try once more

didn't work once again unfortunately

**Comment by ProjectXsent** [comment]
> 
> didn't work once again unfortunately

Does DDMK work tho?

**Comment by Delta21X** [comment]
> > didn't work once again unfortunately
> 
> Does DDMK work tho?

i only was ever able to get that to work once, it would crash on that one too but it was able to open once and work but the moment i closed the game it wasn't able to work again

**Comment by ProjectXsent** [comment]
Probably need to re-install the Visual C++ 2022

**Comment by Delta21X** [comment]
> Probably need to re-install the Visual C++ 2022

unfortunately still crashed, lasted a couple seconds longer this time though, just not enough to get past the first loading screen

**Comment by itsjazzkun** [comment]
same i tried all of it 
@ProjectXsent  told nothing worked

**Comment by SomaBenjamin** [comment]
> I skipped the first apply_patch procedure because I already got the downgraded exes from [here](https://github.com/serpentiem/ddmk/issues/348#issuecomment-2832584543) and I only extracted the Crimson and data folder, Crimson.dll, dinput8.dll, libmpg123-0.dll and the 2 SDL2 dll files. I also ran the apply_patch inside the data folder then the game ran fine with the mod on my end.

![Image](https://github.com/user-attachments/assets/90da27af-dbed-4b71-b468-b94f94669f5b)
This is what I get doing that.

**Comment by ProjectXsent** [comment]
> Nah, I have installed game in C drive, but the same trouble. I have pirated version of this game, probably it only works with buying variant.

Bought the game as well but copied the game folder and used Goldberg (so technically it kinda looks like pirated) but the mod runs fine by it.

**Comment by riwaz99** [comment]
@everyone just drag the 2 exe over the xdelta3 and it will auto patch itself and the data folder apply.bat should work fine. otherwise just share the patched files among yourselves

**Comment by SomaBenjamin** [comment]
> [@everyone](https://github.com/everyone) just drag the 2 exe over the xdelta3 and it will auto patch itself and the data folder apply.bat should work fine. otherwise just share the patched files among yourselves

Tried it, still not working... DMC3.exe only opens HD Collection.

**Comment by IIMM7** [comment]
SOLVED for me, don't patch the game, just copy the new files into the installation folder and run the apply patch inside gdata.afs. ONLY IF YOU ALREADY HAVE THE DDMK WORING

**Comment by SomaBenjamin** [comment]
> SOLVED for me, don't patch the game, just copy the new files into the installation folder and run the apply patch inside gdata.afs. ONLY IF YOU ALREADY HAVE THE DDMK WORING

Ok, I solved with a similar way: I deleted all mods for DMC3, then I installed this.
Keep in mind, you should go to your Steam DB to back up your savefiles before doing saves in game!

**Comment by Max-Riley1** [comment]
it still doesnt work for me i downloaded the DDMK still gives me the patch failed can anyone help?

**Comment by SomaBenjamin** [comment]
Did you downgrade?

**Comment by Max-Riley1** [comment]
> Did you downgrade?

yeah i downloaded the "here" link
